debug: true

springfox-swagger2:
  enabled: true
  api-info:
    title: example
    description: foobar
    version: 0.0.1
    terms-of-service-url: https://www.google.com
    contact:
      name: Lily
      url: https://www.v2ex.com
      email: example@gmail.com
    license: Apache-2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0
  excludedPaths:
    - /error
    - /actuator.*
